name: mimiciv_env
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=19.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - expat=2.7.1
  - gflags=2.2.2
  - glog=0.5.0
  - icu=70.1
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=21.1.5
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgrpc=1.71.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.30
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - llvm-openmp=21.1.5
  - lz4-c=1.9.4
  - ncurses=6.5
  - openssl=3.5.4
  - orc=2.1.1
  - pyarrow=19.0.0
  - python=3.11.13
  - python_abi=3.11
  - re2=2024.07.02
  - readline=8.2
  - setuptools=80.9.0
  - snappy=1.2.2
  - sqlite=3.50.2
  - tk=8.6.15
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.11.0
    - appnope==0.1.4
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.0
    - async-lru==2.0.5
    - attrs==25.4.0
    - babel==2.17.0
    - beautifulsoup4==4.14.2
    - black==25.9.0
    - bleach==6.3.0
    - captum==0.8.0
    - certifi==2025.10.5
    - cffi==2.0.0
    - cfgv==3.4.0
    - charset-normalizer==3.4.4
    - click==8.3.0
    - cloudpickle==3.1.2
    - comm==0.2.3
    - contourpy==1.3.3
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - distlib==0.4.0
    - duckdb==1.4.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.20.0
    - fonttools==4.60.1
    - fqdn==1.5.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - hydra-core==1.3.2
    - identify==2.6.15
    - idna==3.11
    - iniconfig==2.3.0
    - ipykernel==7.1.0
    - ipython==9.7.0
    - ipython-pygments-lexers==1.1.1
    - ipywidgets==8.1.8
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.2
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.9.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.4.10
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.28.0
    - jupyterlab-widgets==3.0.16
    - kiwisolver==1.4.9
    - lark==1.3.1
    - lightning-utilities==0.15.2
    - llvmlite==0.45.1
    - markupsafe==3.0.3
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - mistune==3.1.4
    - mpmath==1.3.0
    - multidict==6.7.0
    - mypy-extensions==1.1.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.5
    - nodeenv==1.9.1
    - notebook==7.4.7
    - notebook-shim==0.2.4
    - numba==0.62.1
    - numpy==1.26.4
    - omegaconf==2.3.0
    - overrides==7.7.0
    - packaging==25.0
    - pandas==2.3.3
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pillow==12.0.0
    - pip==25.3
    - platformdirs==4.5.0
    - pluggy==1.6.0
    - polars==1.35.1
    - polars-runtime-32==1.35.1
    - pre-commit==4.3.0
    - prometheus-client==0.23.1
    - prompt-toolkit==3.0.52
    - propcache==0.4.1
    - psutil==7.1.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.23
    - pygments==2.19.2
    - pyparsing==3.2.5
    - pytest==8.4.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==4.0.0
    - pytokens==0.3.0
    - pytorch-lightning==2.5.6
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.37.0
    - requests==2.32.5
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rpds-py==0.28.0
    - ruff==0.14.3
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - seaborn==0.13.2
    - send2trash==1.8.3
    - shap==0.49.1
    - six==1.17.0
    - slicer==0.0.8
    - sniffio==1.3.1
    - soupsieve==2.8
    - stack-data==0.6.3
    - sympy==1.14.0
    - terminado==0.18.1
    - threadpoolctl==3.6.0
    - tinycss2==1.4.0
    - torch==2.2.2
    - torchmetrics==1.8.2
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - uri-template==1.3.0
    - urllib3==2.5.0
    - virtualenv==20.35.4
    - wcwidth==0.2.14
    - webcolors==25.10.0
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - widgetsnbextension==4.0.15
    - yarl==1.22.0
prefix: /Users/pushpa/opt/anaconda3/envs/mimiciv_env
